### PR TITLE
Always apply double quotes to database and table name

### LINKED ISSUE #153: Issues about when to quote database/tables
**What happened**:

Ever since we upgraded to 1.5.0 from 1.4.x, we had to fix how we are sending in
our default database name and table names. We have to explicitly wrap our
values in `""`. Otherwise, when you go to explore Timestream datasource,
the Database and Table Macro dropdowns are not prepopulated with our values.

**What you expected to happen**:

We expect that timestream plugin to be smart and handle the quoting for us,
I.e. if `defaultDatabase` is `my_test_db` or `"my_test_db"` it should handle
the correct quoting when being supplied to timestream APIs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Using a docker container with timestream 1.5.0 plugin installed
2. Using the following `/etc/grafana/provisioning/datasources/timestream.yaml`:
    ```
    apiVersion: 1

    datasources:
      - name: Timestream
        type: grafana-timestream-datasource
        jsonData:
          authType: default

          # Default timestream variables
          defaultDatabase: "${GF_TIMESTREAM_DEFAULT_DATABASE_NAME}"
          defaultTable: "${GF_TIMESTREAM_DEFAULT_TABLE_NAME}"
    ``` 
3. Sending the following variables:
   * GF_TIMESTREAM_DEFAULT_DATABASE_NAME: "my_test_db"
   * GF_TIMESTREAM_DEFAULT_TABLE_NAME: "my_test_table"    

4. Go to Explore -> Select Timestream Datasource

5. View the Macros table and see that it is empty

To fix the above issue, you need to explicitly wrap `'"my_test_db"'` and `'"my_test_table"'`.
You could also maybe able to change the yaml to include the explicit quoting, but I haven't
tried that.

**Anything else we need to know?**:

FYI, we have this fixed. It's more a UX issue for others. Just need to make sure that
things are quoted in the correct places, which again could be done with the plugin.

**Environment**:
- Grafana version: v8.3.4 (a551d74b1)
- Plugin version: 1.5.0
- OS Grafana is installed on: Official grafana docker container + layers to add plugin installation
- User OS & Browser: Safari 15.3 (17612.4.9.1.8)

### PR DESCRIPTION
**Pull request by fridgepoet**
Providing names via the UI (i.e. config editor page) saves the names with `"` double quotes.
In some recent refactoring, we no longer add double quotes when providing names directly from a provisioning file.

This PR checks if the name is already double quoted (for example provided from UI) and if not adds in the quotes (for example provided from provisioning file). 

Fixes #153

### CODE REVIEW

File: pkg/timestream/datasource.go [hunk 1]
```diff
@@ -234,7 +234,7 @@ func (ds *timestreamDS) CallResource(ctx context.Context, req *backend.CallResou
 		}
 		// TODO: Use API endpoint to list tables
 		v, err := ds.Runner.runQuery(ctx, &timestreamquery.QueryInput{
-			QueryString: aws.String(fmt.Sprintf("SHOW TABLES FROM %s", opts.Database)),
+			QueryString: aws.String(fmt.Sprintf("SHOW TABLES FROM %s", applyQuotesIfNeeded(opts.Database))),
```
Comment (andresmgot) [inline pkg/timestream/datasource.go:237]: the same will be needed for the query in the line 255

File: pkg/timestream/datasource_test.go [hunk 2]
```diff
@@ -117,3 +127,35 @@ func TestCallResource(t *testing.T) {
...
+			Method: "POST",
+			Path:   "tables",
+			Body:   []byte(`{"database":"db"}`),
+		}, sender))
+
+		require.Len(t, mockRunner.calls.runQuery, 1)
+		assert.Equal(t, &timestreamquery.QueryInput{QueryString: aws.String(`SHOW TABLES FROM "db"`)}, mockRunner.calls.runQuery[0])
+	})
+
+	t.Run("db name provided with quotes runs query with db name as-is", func(t *testing.T) {
```
Comment (andresmgot) [inline pkg/timestream/datasource_test.go:147]: can you make these a table test? (you will need two similar ones for the other query type).

**Review by andresmgot — COMMENTED** [review]
Thanks! There is one more thing to quote

File: pkg/timestream/datasource.go (hunk 1 above)
Comment (fridgepoet) [reply pkg/timestream/datasource.go:237]: Thanks, missed that

File: pkg/timestream/datasource_test.go (hunk 2 above)
Comment (fridgepoet) [reply pkg/timestream/datasource_test.go]: I don't prefer the back-and-forth movement in order to read table tests... but going to try that out! Done.

However the names of the tests which I had before feel like too much... I like the explanation when I read them but right now it's cluttering. Any thoughts?

File: pkg/timestream/datasource.go [hunk 3]
```diff
@@ -252,7 +252,7 @@ func (ds *timestreamDS) CallResource(ctx context.Context, req *backend.CallResou
 			return err
 		}
 		v, err := ds.Runner.runQuery(ctx, &timestreamquery.QueryInput{
-			QueryString: aws.String(fmt.Sprintf("SHOW MEASURES FROM %s.%s", opts.Database, opts.Table)),
+			QueryString: aws.String(fmt.Sprintf("SHOW MEASURES FROM %s.%s", applyQuotesIfNeeded(opts.Database), opts.Table)),
```
Comment (andresmgot) [inline pkg/timestream/datasource.go:255]: the table also needs quoting :)

File: pkg/timestream/datasource.go [hunk 4]
```diff
@@ -266,3 +266,10 @@ func (ds *timestreamDS) CallResource(ctx context.Context, req *backend.CallResou
 	}
 	return fmt.Errorf("unknown resource")
 }
+
+func applyQuotesIfNeeded(dbName string) string {
```
Comment (andresmgot) [inline pkg/timestream/datasource.go:270]: nit: replace dbName with input

File: pkg/timestream/datasource_test.go (hunk 2 above)
Comment (andresmgot) [reply pkg/timestream/datasource_test.go]: yeah, since the title already explains the goal of the test (`Test_runQuery_always_sends_name_with_quotes`) you can skip the name, it can be inferred from the input-output

File: pkg/timestream/datasource.go (hunk 3 above)
Comment (fridgepoet) [reply pkg/timestream/datasource.go]: yikes thanks

File: pkg/timestream/datasource_test.go [hunk 5]
```diff
@@ -117,3 +127,99 @@ func TestCallResource(t *testing.T) {
...
+					Body:   []byte(test.requestBody),
+				}, &fakeSender{}))
+
+			require.Len(t, mockRunner.calls.runQuery, 1)
+			assert.Equal(t, &timestreamquery.QueryInput{QueryString: &test.expectedQuery}, mockRunner.calls.runQuery[0])
+		})
+	}
+}
+
+func Test_runQuery_always_sends_table_name_with_quotes(t *testing.T) {
```
Comment (andresmgot) [inline pkg/timestream/datasource_test.go:184]: I would merge this test with the one above (and just quote the database and the table in the same test) but up to you!

**Review by andresmgot — APPROVED** [review]
LGTM, thanks!
