### PR TITLE
Bug Fix :  Fix panic while parsing null timestamps

### LINKED ISSUE #162: Error parsing NULL timestamp value in non scalar measure value
**What happened**:
In a table with both scalar and non-scalar (multi measure) measure values, query `select DemoMetricMultiMeasure6 from "AtlasPDXDevTimestreamDatabase"."dev-mes-multi-measure-test" where measure_name = 'DemoMetric11'` succeeds but query `select DemoMetricMultiMeasure6 from "AtlasPDXDevTimestreamDatabase"."dev-mes-multi-measure-test"` fails with exception

```
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg="panic: runtime error: invalid memory address or nil pointer dereference"
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg="[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc032fe]"
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg=
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg="goroutine 53 [running]:"
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg=github.com/grafana/timestream-datasource/pkg/timestream.datumParserTimestamp(0x19?)
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg="\t/drone/src/pkg/timestream/parsers.go:214 +0x1e"
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg=github.com/grafana/timestream-datasource/pkg/timestream.QueryResultToDataFrame(0xc000153e00)
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg="\t/drone/src/pkg/timestream/helper.go:92 +0xb5e"
logger=plugin.grafana-timestream-datasource t=2022-04-15T21:18:31.05+0000 lvl=dbug msg="github.com/grafana/timestream-datasource/pkg/timestream.ExecuteQuery({_, _}, {{0xc0002960f0, 0x22}, {0x0, 0x0}, {0xc000038260, 0x1f}, {0xc000038280, 0x1c}, ...}, ...)"
```

Measure name `DemoMetric11` stores non-scalar values where `DemoMetricMultiMeasure6` is a timestamp field in the non-scalar measure value. There are other measures in the same table with scalar values too. So the second query (without measure name predicate) will return null values for `DemoMetricMultiMeasure6`.

**What you expected to happen**:
Query should not fail with an exception
 
**How to reproduce it (as minimally and precisely as possible)**:

**Screenshots**

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Plugin version: Current
- OS Grafana is installed on:
- User OS & Browser:
- Others:

### PR DESCRIPTION
**Pull request by yaelleC**
When Timestream returns null timestamps, we get a panic error from the parser, I added a check for it.

Fixes #162

### CODE REVIEW

File: pkg/timestream/parsers.go [hunk 1]
```diff
@@ -209,8 +209,9 @@ func datumParserFloat64(datum *timestreamquery.Datum) (interface{}, error) {
 }
 
 func datumParserTimestamp(datum *timestreamquery.Datum) (interface{}, error) {
-	// 2020-03-18 17:26:30.00000000
-	// 2006-01-02 15:04:05.99999999
+	if datum.ScalarValue == nil {
+		return nil, nil
+	}
```
Comment (yaelleC) [inline pkg/timestream/parsers.go:214]: This is the bug fix, the rest of the changes are test-related

**Review by andresmgot — APPROVED** [review]
:star:

**Review by kevinwcyu — APPROVED** [review]
🙌
