### PR TITLE
Quote and join multiple variables

### LINKED ISSUE #107: Selecting multiple values in a variable results in malformed query
If we create a variable that allows multiple values to be selected, then selecting multiple values results in the variable expanding to incorrect syntax.

For instance, assume I have a variable ``$region`` where during its creating, I select "multi-value" as ON.

When I select multiple values, the variable examples to query text as: ``region = '{us-east-1,eu-west-1}'`` which is incorrect. 

There are two issues here:

1. We're using ``{}`` instead of ``()`` which is needed when passing multiple values.
2. Since in the Timestream data source, varchar variables aren't quoted appropriately, the query is written as ``region = '${region}'`` and it becomes a problem when expanding to multiple selection. Ideally, we'd like the query to be written as ``region IN ($region)`` and the variable to be expanding into ``region IN ('us-east-1')`` or ``region IN ('us-east-1', 'eu-west-1')`` depending on the number of values being selected. However, the quoting is needed only for variable that are VARCHAR and not double or integer. So we need to come up with a way to work out. Even if we do not handle the quoting, I can think of a way where the variables can be created with appropriate quoting, but then at least the variable should expand to ``('us-east-1', 'eu-west-1')``.

### PR DESCRIPTION
**Pull request by andresmgot**
Fixes #107

As we do in [athena](https://github.com/grafana/athena-datasource/blob/main/src/datasource.ts#L37), quote and join variables if they have multiple values.

Screenshot from 2021-11-26 15-32-58

### CODE REVIEW

File: src/DataSource.ts [hunk 1]
```diff
@@ -55,6 +55,21 @@ export class DataSource extends DataSourceWithBackend<TimestreamQuery, Timestrea
     return query.rawQuery ?? '';
   }
 
+  private interpolateVariable = (value: string | string[]) => {
```
Comment (vickyyyyyyy) [inline src/DataSource.ts:58]: nice, I'm guessing this is maybe something that can be shared in the sdk or maybe elsewhere if we are reusing this in multiple plugins?

File: src/DataSource.ts [hunk 2]
```diff
@@ -55,6 +55,21 @@ export class DataSource extends DataSourceWithBackend<TimestreamQuery, Timestrea
...
+      return value;
+    }
+
+    const quotedValues = value.map((v) => {
+      return this.quoteLiteral(v);
+    });
+    return quotedValues.join(',');
+  };
+
+  private quoteLiteral(value: any) {
```
Comment (vickyyyyyyy) [inline src/DataSource.ts:69]: I know this was copied from Athena but should this value also be `string` if we are doing a map of the value that is `string[]`?

File: src/DataSource.ts [hunk 3]
```diff
@@ -72,7 +87,7 @@ export class DataSource extends DataSourceWithBackend<TimestreamQuery, Timestrea
       database: templateSrv.replace(query.database || '', scopedVars),
       table: templateSrv.replace(query.table || '', scopedVars),
       measure: templateSrv.replace(query.measure || '', scopedVars),
-      rawQuery: templateSrv.replace(query.rawQuery, queryScopedVars),
+      rawQuery: templateSrv.replace(query.rawQuery, queryScopedVars, this.interpolateVariable),
```
Comment (vickyyyyyyy) [inline src/DataSource.ts:90]: is there a way of testing this?

**Review by vickyyyyyyy — APPROVED** [review]

File: src/DataSource.ts (hunk 1 above)
Comment (andresmgot) [reply src/DataSource.ts:58]: yes! I have a point in the design document to try to use a common class that cover this

File: src/DataSource.ts (hunk 2 above)
Comment (andresmgot) [reply src/DataSource.ts:69]: let me verify, I believe you are right. Is it supported to have template variables for other things than strings?

File: src/DataSource.ts (hunk 3 above)
Comment (andresmgot) [reply src/DataSource.ts:90]: I was discouraged by the fact that there were no test at all for this class but yes, in this case it can be useful for the future.
