### PR TITLE
Pass `scopedVars` without `$__interval_ms` when interpolating

### LINKED ISSUE #22: Repeated panels does not work
When creating a repeated panel using a multi value variable each value is resolved to the full array.

# Example
Given multi value variable `myVar` containing values `a`, `b` and `c`,
I expect `$myVar` in a repeated panel to resolve to `a` or `b` or `c` depending on the panel index,
but `$myVar` resolves to `{a,b,c}` in all panels.

image

I'm using Grafana v7.3.4 (14c494085e) with Amaxon Timestream 1.0.0

<details><summary>Here's the dashboard I used</summary>
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "description": "Example of a dashboard with repeated panels",
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1607008035519,
  "links": [],
  "panels": [
    {
      "datasource": "Amazon Timestream",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null,
            "filterable": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 8,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.3.4",
      "repeat": "myVar",
      "repeatDirection": "v",
      "scopedVars": {
        "myVar": {
          "selected": true,
          "text": "a",
          "value": "a"
        }
      },
      "targets": [
        {
          "queryType": "raw",
          "rawQuery": "select '$myVar'",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "This works -> $myVar",
      "type": "table"
    },
    {
      "datasource": "Amazon Timestream",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null,
            "filterable": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 8,
        "x": 0,
        "y": 9
      },
      "id": 3,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.3.4",
      "repeatDirection": "v",
      "repeatIteration": 1607008035519,
      "repeatPanelId": 2,
      "scopedVars": {
        "myVar": {
          "selected": true,
          "text": "b",
          "value": "b"
        }
      },
      "targets": [
        {
          "queryType": "raw",
          "rawQuery": "select '$myVar'",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "This works -> $myVar",
      "type": "table"
    },
    {
      "datasource": "Amazon Timestream",
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null,
            "filterable": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 8,
        "x": 0,
        "y": 18
      },
      "id": 4,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.3.4",
      "repeatDirection": "v",
      "repeatIteration": 1607008035519,
      "repeatPanelId": 2,
      "scopedVars": {
        "myVar": {
          "selected": true,
          "text": "c",
          "value": "c"
        }
      },
      "targets": [
        {
          "queryType": "raw",
          "rawQuery": "select '$myVar'",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "This works -> $myVar",
      "type": "table"
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": true,
          "tags": [],
          "text": [
            "a",
            "c",
            "b"
          ],
          "value": [
            "a",
            "c",
            "b"
          ]
        },
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": true,
        "name": "myVar",
        "options": [
          {
            "selected": true,
            "text": "a",
            "value": "a"
          },
          {
            "selected": true,
            "text": "b",
            "value": "b"
          },
          {
            "selected": true,
            "text": "c",
            "value": "c"
          }
        ],
        "query": "a,b,c",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Example dashboard",
  "uid": null,
  "version": 0
}
```
</details>

### PR DESCRIPTION
**Pull request by tiratatp**
## Why is this change required?
- We need to pass `scopedVars` if we want repeating panel to work
- This will fix #22 

## How does this change solve the issue?
- Due to a comment about `DO NOT include scopedVars! it uses
$__interval_ms!!!!!`, we remove the value from `scopedVars` before
passing it

## Does this commit cause any expected behaviors to change? If so, what?
- None

### CODE REVIEW

File: src/DataSource.ts [hunk 1]
```diff
@@ -56,13 +56,17 @@ export class DataSource extends DataSourceWithBackend<TimestreamQuery, Timestrea
       return query;
     }
 
+    // create a copy of scopedVars without $__interval_ms for using with rawQuery
+    var scopedVarsWithoutTimestamp = Object.assign({}, scopedVars);
+    delete scopedVars.__interval_ms;
```
Comment (ryantxu) [inline src/DataSource.ts:61]: Maybe something like:
```suggestion
    const {__interval_ms, __interval, ...queryScopedVars} = scopedVars;
```
